baseURL: "https://rzlwldn.netlify.app/"
languageCode: "en-us"
title: "rzlwldn"
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: UA-166863048-1

params:
  env: production
  description: "Software Engineer, Fast Learner, Cinta linux, Suka Ngopi"
  author: RizalWildan
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  # ShowShareButtons: true
  homeInfoParams:
    Title: Hi there
    content: Software Engineer, Fast Learner, Cinta linux, Suka Ngopi

  socialIcons:
    - name: "github"
      url: "https://github.com/rzlwldn"
    - name: "twitter"
      url: "https://twitter.com/rzlwldn"

  assets:
    disableHLJS: true

menu:
  main:
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

privacy:
  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
